wandb_version: 1

DTA_hidden_dim:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1672960237.861688
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.13.3
      8:
      - 3
      - 8
clf_num_layers:
  desc: null
  value: 2
dropout:
  desc: null
  value: 0.3
lr:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: adam
rank_input:
  desc: null
  value: w
tokenization:
  desc: null
  value: bpe
tree_hidden_dim:
  desc: null
  value: 300
use_batchnorm:
  desc: null
  value: true
